version: '3'

services:
  # payload:
  #   image: node:18-alpine
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - .:/home/node/app
  #     - node_modules:/home/node/app/node_modules
  #   working_dir: /home/node/app/
  #   command: sh -c "yarn install && yarn dev"
  #   depends_on:
  #     - mongo
  #   env_file:
  #     - .env

  postgres:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_DB=cms
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    restart: unless-stopped



volumes:
  data:
  node_modules:
